### PR TITLE
Fix scripts for non unicode directory names

### PR DESCRIPTION
**Pull request by 2press**
Potential fix for my issue in https://github.com/JMSwag/PyUpdater/issues/88

### CODE REVIEW

**Comment by 2press** [comment]
It doesn't fix the issue.

**Comment by 2press** [comment]
In combination with adding `chcp 65001` to the batch scripts this fork should now fix this issue.

**Comment by JMSwag** [comment]
@2press Thanks for the PR!

**Comment by JMSwag** [comment]
@2press Please rebase on develop so I can merge.

**Comment by 2press** [comment]
@JMSwag Rebased on develop.

**Comment by JMSwag** [comment]
@2press TY!

**Pull request merged**
