### PR TITLE
Fix for Key Signing MemoryError 

### PR DESCRIPTION
**Pull request by 2press**
I was able to fix issue https://github.com/JMSwag/PyUpdater/issues/45 with these changes on Windows 10 with Python 3.7.2 64-bit.

### CODE REVIEW

**Comment by JMSwag** [comment]
@2press Thanks for the PR! Would you mind moving the requirement to the setup.py file with a conditional of using pure25519 only on windows with 64bit python and ed25519 otherwise & updating the import statements to try to import ed25519 then fallback to pure25519?

**Comment by 2press** [comment]
@JMSwag No, I wouldn't mind. But trying to import ed25519 and fallback to pure25519 would mean that, if for some reason ed25519 was already installed (possibly by an older version of PyUpdater), the bug would still persist. I would suggest to test for 64-bit windows there as well. 

Is there a reason why you are reluctant to move from ed25519 to pure25519?

**Comment by 2press** [comment]
There seems to be a new issue with travis on MacOS an Python 2.7:
```python@2 2.7.15_1 is already installed
To upgrade to 2.7.15_2, run `brew upgrade python@2`
The command "brew install python@2" failed and exited with 1 during .
```
EDIT: Its now working again due the fix in https://github.com/JMSwag/PyUpdater/pull/142/commits/dfeb308867b935ffb0dbee4938ee13635ce67a6a.

Moreover the detection of "Windows 64-bit" on appveyor seems to be not working as ed25519 is installed by `setup.py` - on my local PC with Windows 10 (64-bit) this is working as indented.

EDIT:  See comments below.

**Comment by 2press** [comment]
@JMSwag Something is wrong with how the AppVeyor environment is currently set up. If you look closely at the log of the latest commit in the official master branch, you notice that all tests where run on Python 2.7 32-bit, see https://ci.appveyor.com/project/JMSwag/pyupdater/build/master-726/job/2b62spr4wob0r7c9#L175.

I have tried to fix this here by https://github.com/JMSwag/PyUpdater/pull/142/commits/678ef6e3cb31f7d35c530ffead28bb968ae22274, but this leads for **all python version except of 2.7 (32-bit) to fail the tests**. 

Moreover PyUpdater seems to to be already installed somehow...
```Installing collected packages: PyUpdater
  Found existing installation: PyUpdater 2.5.3+36.gc061cf5
    Can't uninstall 'PyUpdater'. No files were found to uninstall.
```
~~This might be a reason why installing `pure25519` instead of `ed25519` is not working.~~
EDIT: Installing `pure25519` instead of `ed25519` is now working as of https://github.com/JMSwag/PyUpdater/pull/142/commits/80a010586086ba2b16e8e19f6c2638f5d0854c4b

**Comment by 2press** [comment]
I seems that I was able to fix the setup of AppVeyor. All tests are now passing and seem to be running on the intended versions of Python. From my point of view the pull request this thus ready to be merged.

**Comment by 2press** [comment]
There seems to be a more elegant way to include the Windows dependency specifications, see https://www.python.org/dev/peps/pep-0508/, but as the `env_var`'s are somewhat restricted, I don't see a way to  query for 64-bit.

**Comment by flutefreak7** [comment]
So is this fix complete or are you guys still working a more elegant way to handle the dependencies?

**Comment by 2press** [comment]
I am not working on it - I am just awaiting a response from @JMSwag as this fix is complete (for me).

**Comment by JMSwag** [comment]
@2press Thanks for the PR & apologies for the delay!

**Comment by flutefreak7** [comment]
Sweet! This fix worked for me, so I'm glad to see it merged. I know it stinks to have OS-specific dependencies, so I thank you for taking the time to ensure Windows support.

**Pull request merged**
