### PR TITLE
fix to wrong directory remove on mac

### PR DESCRIPTION
**Pull request by moscoquera**
this is the fix for #91 and workarround for #92 , it was necessary to add a windowed mode test to find the root of the bug on OSX. also added the travis OSX support as mentioned by @cbenhagen in #92 , but it fails because there's not a python 3.4 and 3.5 version for osx, so i ended removing those.

i'm not fluent on tox or travis, so any advice regarding the osx support is welcome.

### CODE REVIEW

**Comment by moscoquera** [comment]
any update?

**Comment by JMSwag** [comment]
@moscoquera Sorry I've been MIA. I'll take a look over this holiday weekend. Today is my Friday.

**Comment by JMSwag** [comment]
@moscoquera Please rebase off the develop branch. I updated the [contributing docs](https://github.com/JMSwag/PyUpdater/blob/develop/docs/contributing.md). Once done I'll merge this & cut a release.

**Comment by moscoquera** [comment]
tests are running!

**Comment by JMSwag** [comment]
@moscoquera Thank you sir!

**Comment by moscoquera** [comment]
looks like the osx build is not running "tox". i'm trying to figure out why.
btw coverage ins't working on appveyor.

**Comment by JMSwag** [comment]
@moscoquera Cool. I hope it isn't anything too tricky.

**Comment by moscoquera** [comment]
@JMSwag this's something on the travis side but i haven't fount the root yet. tox is running correctly on my VM. tried rerunning the "working" build on travis again and isn't working now, so the problem is mostly travis related.

**Comment by JMSwag** [comment]
@moscoquera Oh I see. Thanks for the PR!

**Comment by moscoquera** [comment]
OSX tests are solve on #100

**Comment by JMSwag** [comment]
@moscoquera You are the man!

**Pull request merged**
