### PR TITLE
support for onedir mode and fix to the download progress hook

### PR DESCRIPTION
**Pull request by moscoquera**
As i needed a way to update my app and is impossible to me bundle it in a single file, i did some modifications to the source code implementing the support for onedir mode. most functions didn't required any modification, just small fixes and considerations.

i did the modifications based on @beniamino38 patch: https://gist.github.com/beniamino38/6fcb742b620085de75c22de340580f96 and #16 

i have only tested it on MAC, i'm going to do the windows's test this week.

BTW, also patched the downloader.py file because i wasn't getting the correct download progress.

### CODE REVIEW

**Comment by moscoquera** [comment]
Update: i had added the windows support for onedir mode. as move is painful moving folders i decided to use robocopy instead. also, changed the old make_archive to use `shutil.make_archive`

**Comment by JMSwag** [comment]
@moscoquera Thanks for the PR! I'll get this merged once I fix the test suite.

**Review by JMSwag — COMMENTED** [review]
This can be merged once the comments below are addressed. Thanks again for this PR!

Add - "/purge" to the robocopy commands
Add - client/updates.py - blank line to end of file
Update - utils/__init__.py Needs some PEP8 love.

**Comment by moscoquera** [comment]
Hi again.
i just added the requested modifications.

**Comment by JMSwag** [comment]
@moscoquera Looks good. Please rebase on master as I've fixed the test suite. Sorry for not mentioning that earlier.

Bouns points if you can add the tests for one dir. Should be pretty straight forward with what's already there.

**Comment by moscoquera** [comment]
I'm running the test suite because some tests are failing. `test_execution_onefile_extract` is calling `build_onefile_extract.py`. and i see the -F option is set, but pyupdater still building a directory instead, what should i modify to build a single file for the test?

**Comment by JMSwag** [comment]
You may need to remove [these](https://github.com/moscoquera/PyUpdater/blob/5d93fd44d6c7a28549df2a794695ef68e933e7d1/pyupdater/cli/options.py#L59-L68) lines or preferably rebase off master.

**Comment by moscoquera** [comment]
finally solved the failing tests, still need to find why isn't working on my OSX, but it worked on windows and linux. i also need to design a test for the onedir support.

**Comment by moscoquera** [comment]
well... i'm unable to find why AppVeyor keeps failing randomly  ╮(￣ω￣;)╭
any advice is welcome

**Comment by JMSwag** [comment]
@moscoquera There is a skeleton of a test for onedir supoprt [here](https://github.com/JMSwag/PyUpdater/blob/master/tests/test_pyupdater.py). With supporting files [here](https://github.com/JMSwag/PyUpdater/blob/master/tests/data/update_repo_extract/build_onedir_extract.py) & [here](https://github.com/JMSwag/PyUpdater/blob/master/tests/data/update_repo_restart/build_onedir_restart.py). Appveyor has been hit or miss for me as well. I'll take a look.

**Comment by moscoquera** [comment]
already modified those and added a copy of app_extract_01 and app_restart_01 setting the custom update directory on the parent folder.

**Comment by moscoquera** [comment]
i have been thinking is due a problem with the lock, because it only fails when custom_dir is false, maybe a race condition on the update folder.

**Comment by moscoquera** [comment]
ok it's working now, changed the thread lock system for filelock to avoid race conditions on the updater folder.

**Comment by JMSwag** [comment]
Looks great! Just touch up these few minor edits & I'll get this PR merged.

[1](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/pyupdater/utils/__init__.py#L284), [2](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/pyupdater/utils/__init__.py#L297), [3](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/pyupdater/utils/__init__.py#L433), [4](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/tests/test_pyupdater.py#L173), [5](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/tests/test_pyupdater.py#L182), [6](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/tests/test_pyupdater.py#L338), [7](https://github.com/JMSwag/PyUpdater/blob/c84186fd764f0dff060085a11aa22bb0cbcd2304/tests/test_pyupdater.py#L347)

**Comment by JMSwag** [comment]
@moscoquera Please squash your commits.

**Comment by moscoquera** [comment]
Sure, no problem. can you tell me what modifications should i do on those lines?

**Comment by JMSwag** [comment]
Mostly PEP8

**Comment by moscoquera** [comment]
changes are made, it's looks working now. i did a previous run and it failed throwing something regarding pyinstaller permissions but rerunning the test again worked seamlessly.

**Comment by JMSwag** [comment]
@moscoquera Are you able to squash these commits into 1?

**Comment by JMSwag** [comment]
@moscoquera I'll get this in the v2.5 release today.

**Comment by moscoquera** [comment]
it's a pleasure and a honor for me.

**Comment by JMSwag** [comment]
@moscoquera Thanks again for this huge PR. Quite a few users have requested this feature.

**Comment by JMSwag** [comment]
Closes #16

**Pull request merged**
